### ISSUE TITLE
Unable to submit Sales Invoice due to Mode of Payment

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext_shopify#131]
Hi,

I have installed Shopify Connector and have troubling syncing paid orders to become a sales invoice.

Received the following error log. Please advice. I have already put the Bank Transfer as the mode of payment.

As mentioned by @saurabh6790 this is an issue.

https://discuss.erpnext.com/t/shopify-integration-mode-of-payment/17712/2

> Traceback (most recent call last):
File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 22, in sync_shopify_orders
create_order(shopify_order, shopify_settings)
File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 54, in create_order
create_sales_invoice(shopify_order, shopify_settings, so)
File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 100, in create_sales_invoice
si.submit()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 726, in submit
self._submit()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 715, in _submit
self.save()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 233, in save
return self._save(*args, **kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 252, in _save
self.insert()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
self.run_post_save_methods()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 774, in run_post_save_methods
self.run_method("on_submit")
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 654, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 882, in composer
return composed(self, method, *args, **kwargs)
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 648, in 
fn = lambda self, args, **kwargs: getattr(self, method)(args, **kwargs)
File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 95, in on_submit
self.validate_pos_paid_amount()
File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 131, in validate_pos_paid_amount
frappe.throw(_("At least one mode of payment is required for POS invoice."))
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 300, in throw
msgprint(msg, raise_exception=exc, title=title, indicator='red')
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 293, in msgprint
raiseexception()
File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 266, in raiseexception
raise raise_exception, encode(msg)
ValidationError: At least one mode of payment is required for POS invoice.

**Comment by addymuliady** [comment]
#https://github.com/frappe/erpnext_shopify/pull/132
