### ISSUE TITLE
attributing shipping income account when creating sales invoice

### ISSUE THREAD

**Issue by hanselke** [frappe/erpnext_shopify#133]
So i have a 'Standard Shipping' charge from shopify, that i mapped to "Shipping Income" under direct income. This is the error that occurs when i sync

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 22, in sync_shopify_orders
    create_order(shopify_order, shopify_settings)
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 54, in create_order
    create_sales_invoice(shopify_order, shopify_settings, so)
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 98, in create_sales_invoice
    si.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 723, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 712, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 233, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 252, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 203, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 753, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 651, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 879, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 862, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 82, in validate
    self.set_against_income_account()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 366, in set_against_income_account
    self.against_income_account = ','.join(against_acc)
TypeError: sequence item 0: expected string or Unicode, NoneType found

**Comment by pratikcws** [comment]
have you find any solution ? same issue with me
