### ISSUE TITLE
Error on Sync - Duplicate Supplier

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext_shopify#139]
Hi I think this is due to the API calling to create a new Supplier. We already have an existing Supplier in ERPNext.
```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 23, in sync_shopify_items
    make_item(warehouse, shopify_item, shopify_item_list)
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 45, in make_item
    create_item(shopify_item, warehouse, shopify_item_list=shopify_item_list)
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 123, in create_item
    "default_supplier": get_supplier(shopify_item)
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 223, in get_supplier
    "supplier_type": get_supplier_type()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 214, in insert
    self.db_insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/base_document.py", line 296, in db_insert
    ), d.values())
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DuplicateEntryError: (u'Supplier', u'IRIS GROUP PTE LTD', IntegrityError(1062, "Duplicate entry 'IRIS GROUP PTE LTD' for key 'PRIMARY'"))
```

**Comment by saurabh6790** [comment]
Fixed in V2.0.4
