### ISSUE TITLE
AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by hanselke** [frappe/erpnext_shopify#141]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/api.py", line 32, in sync_shopify_resources
    sync_products(shopify_settings.price_list, shopify_settings.warehouse)
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 16, in sync_products
    sync_shopify_items(warehouse, shopify_item_list)
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 30, in sync_shopify_items
    if e.args[0] and e.args[0].startswith("402"):
AttributeError: 'int' object has no attribute 'startswith'

**Comment by yashodhank** [comment]
**Installed Apps**

- ERPNext: v8.3.5 (master)
- ERPNext Shopify: v2.0.10 (develop)
- Frappe Framework: v8.3.8 (master)


```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/api.py", line 32, in sync_shopify_resources
    sync_products(shopify_settings.price_list, shopify_settings.warehouse)
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 16, in sync_products
    sync_shopify_items(warehouse, shopify_item_list)
  File "/home/frappe/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 30, in sync_shopify_items
    if e.args[0] and e.args[0].startswith("402"):
AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by joehosemann** [comment]
Having this issue too.

**Comment by arefaii** [comment]
Any update on this ticket
