### ISSUE TITLE
Error when create customer address

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext_shopify#157]
ERPNext: v8.0.44 (master)

ERPNext Shopify: v2.0.10 (master)

Frappe Framework: v8.0.64 (master)
```

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 73, in create_customer_address
    "link_name": customer.name
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 193, in insert
    self._validate()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 401, in _validate
    self._validate_selects()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/base_document.py", line 540, in _validate_selects
    value, comma_options))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 306, in msgprint
    _raise_exception()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 279, in _raise_exception
    raise raise_exception, encode(msg)
ValidationError:  Address Type cannot be "Billing". It should be one of "Landed", "Condominium", "Residential", "Office", "Airport", "Restricted Areas"
```

**Comment by addymuliady** [comment]
Customize Form
Address
Added Billing to Address Type option
