### ISSUE TITLE
Error when create customer

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext_shopify#158]
ERPNext: v8.0.44 (master)

ERPNext Shopify: v2.0.10 (master)

Frappe Framework: v8.0.64 (master)
```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 42, in create_customer
    create_customer_address(customer, shopify_customer)
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 55, in create_customer_address
    for i, address in enumerate(shopify_customer.get("addresses")):
TypeError: 'NoneType' object is not iterable
```

**Comment by addymuliady** [comment]
Customize Form
Address
Added Billing to Address Type option
