### ISSUE TITLE
Error when sync shopify resources

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext_shopify#159]
ERPNext: v8.0.44 (master)

ERPNext Shopify: v2.0.10 (master)

Frappe Framework: v8.0.64 (master)
```
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/api.py", line 34, in sync_shopify_resources
    sync_orders()
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 13, in sync_orders
    sync_shopify_orders()
  File "/home/ubuntu/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 29, in sync_shopify_orders
    if e.args and e.args[0] and e.args[0].startswith("402"):
AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by addymuliady** [comment]
@saurabh6790 dun mind taking a look at this? thanks.
