### ISSUE TITLE
Shopify issue:  Row 2: Conversion Factor is mandatory

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext_shopify#163]
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 22, in sync_shopify_orders
    create_order(shopify_order, shopify_settings)
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 52, in create_order
    so = create_sales_order(shopify_order, shopify_settings, company)
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 83, in create_sales_order
    so.save(ignore_permissions=True)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 253, in _save
    self.insert()
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 192, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 887, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 870, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 29, in validate
    super(SalesOrder, self).validate()
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext/erpnext/controllers/selling_controller.py", line 36, in validate
    self.set_qty_as_per_stock_uom()
  File "/home/frappe/benches/bench-2017-07-18/apps/erpnext/erpnext/controllers/selling_controller.py", line 168, in set_qty_as_per_stock_uom
    frappe.throw(_("Row {0}: Conversion Factor is mandatory").format(d.idx))
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-07-18/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Row 2: Conversion Factor is mandatory
```

**Comment by StrikingEnergy** [comment]
Any movement on this issue Saura?  We keep getting this error
