### ISSUE TITLE
Error with V10.0.5

### ISSUE THREAD

**Issue by malcolmjay** [frappe/erpnext_shopify#184]
I'm receiving the following error after updating to V10.0.5 when trying to sync to Shopify via a private app:

Traceback (most recent call last):
  File "/home/malcolm_jamal/frappe-bench/apps/erpnext_shopify/erpnext_shopify/api.py", line 32, in sync_shopify_resources
    sync_products(shopify_settings.price_list, shopify_settings.warehouse)
  File "/home/malcolm_jamal/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 18, in sync_products
    sync_erpnext_items(price_list, warehouse, shopify_item_list)
  File "/home/malcolm_jamal/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 338, in sync_erpnext_items
    for item in get_erpnext_items(price_list):
  File "/home/malcolm_jamal/frappe-bench/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 366, in get_erpnext_items
    erpnext_items.extend(frappe.db.sql(item_from_master, as_dict=1))
  File "/home/malcolm_jamal/frappe-bench/apps/frappe/frappe/database.py", line 176, in sql
    self._cursor.execute(query)
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/malcolm_jamal/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'net_weight' in 'field list'")

**Comment by aerodss** [comment]
Hi sorry to bump this thread but I'm having the same error.
After updating bench and installed woocommerce connector, sync fails with this error:

_Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext_woocommerce/erpnext_woocommerce/api.py", line 32, in sync_woocommerce_resources
    sync_products(woocommerce_settings.price_list, woocommerce_settings.warehouse)
  File "/home/frappe/frappe-bench/apps/erpnext_woocommerce/erpnext_woocommerce/sync_products.py", line 18, in sync_products
    sync_erpnext_items(price_list, warehouse, woocommerce_item_list)
  File "/home/frappe/frappe-bench/apps/erpnext_woocommerce/erpnext_woocommerce/sync_products.py", line 322, in sync_erpnext_items
    for item in get_erpnext_items(price_list):
  File "/home/frappe/frappe-bench/apps/erpnext_woocommerce/erpnext_woocommerce/sync_products.py", line 350, in get_erpnext_items
    erpnext_items.extend(frappe.db.sql(item_from_master, as_dict=1))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 209, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'net_weight' in 'field list'")_

**Comment by aerodss** [comment]
This are my versions

frappe@erp:~/frappe-bench$ bench version
erpnext 10.1.42
erpnext_shopify 2.0.26
erpnext_woocommerce 1.0.0
frappe 10.1.39
