### ISSUE TITLE
[Scheduler] Attribute does not exist in the list of valid Item Attribute Values

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#29]
```
The contents of the full traceback was:

Traceback (most recent call last):
 File "/home/frappe/v5press/benches/1601081621/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/v5press/benches/1601081621/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 63, in sync_shopify
   sync_products(shopify_settings.price_list, shopify_settings.warehouse)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 75, in sync_products
   sync_shopify_items(warehouse)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 80, in sync_shopify_items
   make_item(warehouse, item)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 86, in make_item
   create_item_variants(item, warehouse, attributes, shopify_variants_attr_list)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 192, in create_item_variants
   create_item(variant_item, warehouse, 0, attributes, template_item.name)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 161, in create_item
   new_item.insert()
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/model/document.py", line 192, in insert
   self.run_before_save_methods()
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/model/document.py", line 589, in run_before_save_methods
   self.run_method("validate")
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/model/document.py", line 551, in run_method
   return Document.hook(fn)(self, *args, **kwargs)
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/model/document.py", line 706, in composer
   return composed(self, method, *args, **kwargs)
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/model/document.py", line 689, in runner
   add_to_return_value(self, fn(self, *args, **kwargs))
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/model/document.py", line 545, in <lambda>
   fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext/erpnext/stock/doctype/item/item.py", line 77, in validate
   self.validate_variant_attributes()
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext/erpnext/stock/doctype/item/item.py", line 575, in validate_variant_attributes
   variant = get_variant(self.variant_of, args, self.name)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext/erpnext/controllers/item_variant.py", line 27, in get_variant
   validate_item_variant_attributes(template, args)
 File "/home/frappe/v5press/benches/1601081621/apps/erpnext/erpnext/controllers/item_variant.py", line 66, in validate_item_variant_attributes
   value, attribute))
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/__init__.py", line 257, in throw
   msgprint(msg, raise_exception=exc)
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/__init__.py", line 250, in msgprint
   _raise_exception()
 File "/home/frappe/v5press/benches/1601081621/apps/frappe/frappe/__init__.py", line 235, in _raise_exception
   raise raise_exception, encode(msg)
ValidationError: Value 36"-66" for Attribute Telescopic (Extendable) SIze does not exist in the list of valid Item Attribute Values
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/pull/35
