### ISSUE TITLE
[scheduler] validate_customer_and_product

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#32]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1601070731/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1601070731/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1601070731/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 65, in sync_shopify
   sync_orders()
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 485, in sync_orders
   sync_shopify_orders()
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 489, in sync_shopify_orders
   validate_customer_and_product(order)
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 493, in validate_customer_and_product
   if not frappe.db.get_value("Customer", {"shopify_id": order.get("customer").get("id")}, "name"):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/pull/39
