### ISSUE TITLE
[scheduler] item image unprocessable

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#33]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1601070731/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1601070731/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1601070731/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 63, in sync_shopify
   sync_products(shopify_settings.price_list, shopify_settings.warehouse)
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 76, in sync_products
   sync_erp_items(price_list, warehouse)
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 269, in sync_erp_items
   sync_item_with_shopify(item, price_list, warehouse)
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 320, in sync_item_with_shopify
   sync_item_image(erp_item)
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 342, in sync_item_image
   post_request("/admin/products/{0}/images.json".format(item.shopify_id), image_info)
 File "/home/frappe/press/benches/1601070731/apps/erpnext_shopify/erpnext_shopify/utils.py", line 112, in post_request
   r.raise_for_status()
 File "/home/frappe/press/benches/1601070731/env/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
HTTPError: 422 Client Error: Unprocessable Entity for url: https://computer-dukaan.myshopify.com//admin/products/3756782081/images.json
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/pull/35
