### ISSUE TITLE
[scheduler] payment required

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#34]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1601070735/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1601070735/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1601070735/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1601070735/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 63, in sync_shopify
   sync_products(shopify_settings.price_list, shopify_settings.warehouse)
 File "/home/frappe/press/benches/1601070735/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 75, in sync_products
   sync_shopify_items(warehouse)
 File "/home/frappe/press/benches/1601070735/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 79, in sync_shopify_items
   for item in get_shopify_items():
 File "/home/frappe/press/benches/1601070735/apps/erpnext_shopify/erpnext_shopify/utils.py", line 15, in get_shopify_items
   for page_idx in xrange(0, get_total_pages("products") or 1):
 File "/home/frappe/press/benches/1601070735/apps/erpnext_shopify/erpnext_shopify/utils.py", line 10, in get_total_pages
   return int(math.ceil(get_request('/admin/{0}/count.json'.format(resource)).get('count', 0) / 250))
 File "/home/frappe/press/benches/1601070735/apps/erpnext_shopify/erpnext_shopify/utils.py", line 104, in get_request
   r.raise_for_status()
 File "/home/frappe/press/benches/1601070735/env/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
HTTPError: 402 Client Error: Payment Required for url: https://mercatino-de-quererte.myshopify.com//admin/products/count.json
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/commit/2744d8be16ba627deb67eee5c80bac144859ce4b
