### ISSUE TITLE
[scheduler] 429 Client Error: Too Many Requests

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#38]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1601131050/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1601131050/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1601131050/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1601131050/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 64, in sync_shopify
   sync_products(shopify_settings.price_list, shopify_settings.warehouse)
 File "/home/frappe/press/benches/1601131050/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 77, in sync_products
   sync_erp_items(price_list, warehouse)
 File "/home/frappe/press/benches/1601131050/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 291, in sync_erp_items
   sync_item_with_shopify(item, price_list, warehouse)
 File "/home/frappe/press/benches/1601131050/apps/erpnext_shopify/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/shopify_settings.py", line 345, in sync_item_with_shopify
   put_request("/admin/products/{}.json".format(item.get("shopify_id")), item_data)
 File "/home/frappe/press/benches/1601131050/apps/erpnext_shopify/erpnext_shopify/utils.py", line 120, in put_request
   r.raise_for_status()
 File "/home/frappe/press/benches/1601131050/env/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
HTTPError: 429 Client Error: Too Many Requests for url: https://computer-dukaan.myshopify.com//admin/products/3788003905.json
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/pull/39
