### ISSUE TITLE
[scheduler] Duplicate Address

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#43]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1601211426/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1601211426/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1601211426/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/api.py", line 26, in sync_shopify
   sync_customers()
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 8, in sync_customers
   sync_shopify_customers()
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 14, in sync_shopify_customers
   create_customer(shopify_customer)
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 38, in create_customer
   create_customer_address(customer, shopify_customer)
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 56, in create_customer_address
   "customer_name":  customer.customer_name
 File "/home/frappe/press/benches/1601211426/apps/frappe/frappe/model/document.py", line 202, in insert
   self.db_insert()
 File "/home/frappe/press/benches/1601211426/apps/frappe/frappe/model/base_document.py", line 276, in db_insert
   ), d.values())
 File "/home/frappe/press/benches/1601211426/apps/frappe/frappe/database.py", line 135, in sql
   self._cursor.execute(query, values)
 File "/home/frappe/press/benches/1601211426/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
   self.errorhandler(self, exc, value)
 File "/home/frappe/press/benches/1601211426/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
   raise errorclass, errorvalue
DuplicateEntryError: ('Address', u'NAME REDACTED-Billing', IntegrityError(1062, "Duplicate entry 'NAME REDACTED-Billing' for key 'PRIMARY'"))
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/pull/45
