### ISSUE TITLE
[scheduler] Address Type Selection

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#44]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1601211426/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1601211426/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1601211426/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/api.py", line 26, in sync_shopify
   sync_customers()
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 8, in sync_customers
   sync_shopify_customers()
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 14, in sync_shopify_customers
   create_customer(shopify_customer)
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 38, in create_customer
   create_customer_address(customer, shopify_customer)
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 46, in create_customer_address
   "address_type": get_address_type(i),
 File "/home/frappe/press/benches/1601211426/apps/erpnext_shopify/erpnext_shopify/utils.py", line 7, in get_address_type
   "Warehouse", "Other"][i]
IndexError: list index out of range
```

**Comment by saurabh6790** [comment]
https://github.com/frappe/erpnext_shopify/pull/45
