### ISSUE TITLE
[scheduler] UnicodeEncodeError

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#62]
```
The contents of the full traceback was:

Traceback (most recent call last):
 File "/home/frappe/press/benches/1602040821/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1602040821/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1602040821/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/api.py", line 29, in sync_shopify_resources
   sync_products(shopify_settings.price_list, shopify_settings.warehouse)
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 19, in sync_products
   sync_shopify_items(warehouse, shopify_item_list)
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 24, in sync_shopify_items
   make_item(warehouse, shopify_item, shopify_item_list)
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 31, in make_item
   create_item_variants(shopify_item, warehouse, attributes, shopify_variants_attr_list, shopify_item_list=shopify_item_list)
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 162, in create_item_variants
   create_item(shopify_item_variant, warehouse, 0, attributes, template_item.name, shopify_item_list=shopify_item_list)
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 123, in create_item
   if not is_item_exists(item_dict, attributes, shopify_item_list=shopify_item_list):
 File "/home/frappe/press/benches/1602040821/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 276, in is_item_exists
   .format(attr.get("attribute"), attr.get("attribute_value")) for attr in attributes]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 16: ordinal not in range(128)
```

---

Solution: use `from __future__ import unicode_literals` in all files like we do in erpnext project

**Comment by anandpdoshi** [comment]
See this: https://github.com/anandpdoshi/erpnext_shopify/blob/refactor/erpnext_shopify/sync_items.py#L4
