### ISSUE TITLE
[Scheduler] - Price List None is disabled

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#71]
```
Traceback (most recent call last):
 File "/home/frappe/press/benches/1602191124/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/press/benches/1602191124/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/tasks.py", line 114, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/api.py", line 29, in sync_shopify_resources
   sync_products(shopify_settings.price_list, shopify_settings.warehouse)
 File "/home/frappe/press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 17, in sync_products
   sync_shopify_items(warehouse, shopify_item_list)
 File "/home/frappe/press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 22, in sync_shopify_items
   make_item(warehouse, shopify_item, shopify_item_list)
 File "/home/frappe/press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 33, in make_item
   create_item(shopify_item, warehouse, shopify_item_list=shopify_item_list)
 File "/home/frappe/press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 126, in create_item
   add_to_price_list(shopify_item, name)
 File "/home/frappe/press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_products.py", line 191, in add_to_price_list
   "price_list_rate": item.get("item_price") or item.get("variants")[0].get("price")
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/model/document.py", line 193, in insert
   self.run_before_save_methods()
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/model/document.py", line 602, in run_before_save_methods
   self.run_method("validate")
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/model/document.py", line 564, in run_method
   return Document.hook(fn)(self, *args, **kwargs)
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/model/document.py", line 720, in composer
   return composed(self, method, *args, **kwargs)
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/model/document.py", line 703, in runner
   add_to_return_value(self, fn(self, *args, **kwargs))
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/model/document.py", line 558, in <lambda>
   fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
 File "/home/frappe/press/benches/1602191124/apps/erpnext/erpnext/stock/doctype/item_price/item_price.py", line 15, in validate
   self.validate_price_list()
 File "/home/frappe/press/benches/1602191124/apps/erpnext/erpnext/stock/doctype/item_price/item_price.py", line 27, in validate_price_list
   throw(_("Price List {0} is disabled").format(self.price_list))
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/__init__.py", line 265, in throw
   msgprint(msg, raise_exception=exc)
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/__init__.py", line 258, in msgprint
   _raise_exception()
 File "/home/frappe/press/benches/1602191124/apps/frappe/frappe/__init__.py", line 243, in _raise_exception
   raise raise_exception, encode(msg)
ValidationError: Price List None is disabled
```

**Comment by JulesThuillier** [comment]
Anyone has a bugfix ?
