### ISSUE TITLE
[Scheduler] Unprocessable Entity 

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_shopify#72]
`*******` => Redacted content

---

```
Traceback (most recent call last):
 File "/home/frappe/v5press/benches/1602191124/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/home/frappe/v5press/benches/1602191124/env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
   return self.run(*args, **kwargs)
 File "/home/frappe/v5press/benches/1602191124/apps/frappe/frappe/tasks.py", line 110, in scheduler_task
   frappe.get_attr(handler)()
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/api.py", line 30, in sync_shopify_resources
   sync_customers()
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 10, in sync_customers
   sync_erpnext_customers(shopify_customer_list)
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 92, in sync_erpnext_customers
   update_customer_to_shopify(customer, last_sync_condition)
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 129, in update_customer_to_shopify
   update_address_details(customer, last_sync_condition)
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 149, in update_address_details
   sync_customer_address(customer, address)
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/sync_customers.py", line 115, in sync_customer_address
   {"address": address})
 File "/home/frappe/v5press/benches/1602191124/apps/erpnext_shopify/erpnext_shopify/shopify_requests.py", line 43, in post_request
   r.raise_for_status()
 File "/home/frappe/v5press/benches/1602191124/env/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
HTTPError: 422 Client Error: Unprocessable Entity for url: https://**************@******.myshopify.com//admin/customers/2594113348/addresses.json
```

**Comment by jitendravarma** [comment]
@anandpdoshi is there any update on above bug, we are facing same issue.

> 422 Client Error: Unprocessable Entity for url: https://XXXXXX:XXXXXXXX@XXXXXX.myshopify.com/admin/api/2019-04/webhooks.json

> Traceback	

> Traceback (most recent call last):
>  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py", line 44, in register_webhooks
>    self.update_webhook_table(method, d.json())
>  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
>    raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://XXXXXX:XXXXXX@XXXXX.myshopify.com/admin/api/2019-04/webhooks.json
